name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  APT_PACKAGES: curl build-essential libgtk-4-dev libgtk4-layer-shell-dev

jobs:
  formatting:
    name: Verify code formatting
    runs-on: ubuntu-24.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v6
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-06-01
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  check_changelog:
    name: Check Changelog
    runs-on: ubuntu-24.04
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md
    if: github.actor != 'dependabot[bot]'
  lint:
    name: Lint
    needs: [ formatting, check_changelog ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    strategy:
      matrix:
        toolchain: [ stable, nightly-2026-06-01 ]
        target: [ x86_64-unknown-linux-gnu ]
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y ${{ env.APT_PACKAGES }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Run cargo clippy
        run: cargo clippy --all-targets --target ${{ matrix.target }}
  build:
    name: Release Build
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
        toolchain: [ stable, nightly-2026-06-01 ]
    runs-on: ${{ matrix.os }}
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y ${{ env.APT_PACKAGES }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Build (Release Mode)
        run: cargo build --release --verbose
  test:
    name: Tests
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    strategy:
      matrix:
        toolchain: [ stable, nightly-2026-06-01 ]
        target: [ x86_64-unknown-linux-gnu ]
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y ${{ env.APT_PACKAGES }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Test (Release Mode)
        run: cargo test --release --verbose --target ${{ matrix.target }}
  docs:
    name: Build Documentation & Book
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Build API Docs
        run: cargo doc --no-deps --document-private-items --workspace --verbose
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Build Book
        run: mdbook build book
