name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  APT_PACKAGES: curl pkg-config libgtk-4-dev libgtk4-layer-shell-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libgles2-mesa-dev libdrm-dev libgbm-dev libinput-dev libudev-dev libxkbcommon-x11-dev meson ninja-build libgirepository1.0-dev

jobs:
  formatting:
    name: Verify code formatting
    runs-on: ubuntu-24.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-06-01
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  check_changelog:
    name: Check Changelog
    runs-on: ubuntu-24.04
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md
    if: github.actor != 'dependabot[bot]'
  lint:
    name: Lint
    needs: [ formatting, check_changelog ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    strategy:
      matrix:
        toolchain: [ stable, nightly-2026-06-01 ]
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.APT_PACKAGES }}
          version: 1.0
      - name: Install musl-tools
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0
        if: matrix.target == 'x86_64-unknown-linux-musl'
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run cargo clippy
        run: cargo clippy --all-targets --target ${{ matrix.target }}
  build:
    name: Release Build
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
        toolchain: [ stable, nightly-2026-06-01 ]
    runs-on: ${{ matrix.os }}
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.APT_PACKAGES }}
          version: 1.0
      - name: Install gtk4-layer-shell from source
        run: |
          git clone https://github.com/wmww/gtk4-layer-shell
          cd gtk4-layer-shell
          meson setup build --prefix=/usr -Dexamples=false -Dtests=false -Dvapi=false
          ninja -C build
          sudo ninja -C build install
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Build (Release Mode)
        run: cargo build --release --verbose
  test:
    name: Tests
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    strategy:
      matrix:
        toolchain: [ stable, nightly-2026-06-01 ]
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ${{ env.APT_PACKAGES }}
          version: 1.0
      - name: Install musl-tools
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0
        if: matrix.target == 'x86_64-unknown-linux-musl'
      - name: Install gtk4-layer-shell from source
        run: |
          git clone https://github.com/wmww/gtk4-layer-shell
          cd gtk4-layer-shell
          meson setup build --prefix=/usr -Dexamples=false -Dtests=false -Dvapi=false
          ninja -C build
          sudo ninja -C build install
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Test (Release Mode)
        run: cargo test --release --verbose --target ${{ matrix.target }}
  docs:
    name: Build Documentation & Book
    needs: [ lint ]
    if: always() && (!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled'))
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Build API Docs
        run: cargo doc --no-deps --document-private-items --workspace --verbose
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Build Book
        run: mdbook build book
