name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  APT_PACKAGES: curl build-essential libgtk-4-dev libgtk4-layer-shell-dev

permissions:
  contents: write

jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:26.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v7
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y ${{ env.APT_PACKAGES }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build (Release Mode)
        run: cargo build --release --verbose
      - name: Publish to crates.io
        run: cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
